<a href="https://colab.research.google.com/github/2101324/dl2022late/blob/main/NumpyReplay2022.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
import numpy as np

In [6]:
x = np.array([1.0, 2.0, 3.0, 4.0,5.0])
print(x)
x = np.array([1,2,3])
print(x)
print(type(x))


[1. 2. 3. 4. 5.]
[1 2 3]
<class 'numpy.ndarray'>


In [7]:
my_list1 = [1,2,3,4,5]
my_array1 = np.array(my_list1)
my_list2 = [10,20,30,40,50]
my_lists = [my_list1, my_list2] # リストのリストを作る。
my_lists # [[1, 2, 3, 4, 5], [10, 20, 30, 40, 50]] # リストのリストが完成。

# my_listsを使ってNumPyのアレイを使る。（多次元配列を作る）
my_array2 = np.array(my_lists)

my_array2 # 2行5列の配列ができる。

array([[ 1,  2,  3,  4,  5],
       [10, 20, 30, 40, 50]])

In [8]:
a = np.array([1, 2, 3, 4])
a.shape # (4,)が出力される。これは1次元配列でかつ、4つ要素があることを意味します。

b = np.array([[1, 2],[3,4]])
b.shape # (2, 2) これは行列で、2行2列を意味しています。

(2, 2)

In [9]:
x = np.arange(10)
print(x)

# reshape()は配列を形状に変換します
x = np.arange(1, 10).reshape(3,3) # 3×3の多次元配列に変換
y = np.arange(1, 10).reshape(3,3) 

[0 1 2 3 4 5 6 7 8 9]


In [12]:
print(x)
print(y)

print(x + y)
print(x - y)
print(x * y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [13]:
sample_array = np.arange(10)
print(sample_array)

# reshapeを使って配列の形状を指定
sample_array2 = sample_array.reshape(2,5)
print(sample_array2) #array(([0,1,2,3,4],[5,6,7,8,9]])

# concatenateを使って、データの結合する(axisで行方向か、縦方向を指定可能)
sample_array3 = np.array([[1,2,3],[4,5,6]])
sample_array4 = np.array([[7,8,9],[10,11,12]])

# 行方向に結合 ([[1,2,3,7,8,9],4,5,6,10,11,12]])
print(np.concatenate([sample_array3,sample_array4],axis=1))

# hstackでも行方向の結合が可能
print(np.hstack((sample_array3,sample_array4)))

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [14]:
print(np.concatenate([sample_array3,sample_array4],axis=0))

# vstackで列方向の結合が可能
print(np.vstack((sample_array3,sample_array4)))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [15]:
sample_array = np.arange(10)
print(sample_array)

# 上記の配列に「5」を足す計算
# 要素をコピーして大きさを揃えて、配列の全ての要素に5を加算
print(sample_array + 5)

[0 1 2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10 11 12 13 14]


In [16]:
n1 = np.array([1,2,3,4,5])
print(n1) # [1 2 3 4 5]

# 配列の次元数は np.ndim() 関数で取得可能
np.ndim(n1) # 1 -> 1次元

# 配列の形状取得にはshapeを使う。タプルでかえってくる
n1.shape # (5,) # 変数n1の形状を取得

[1 2 3 4 5]


(5,)

In [17]:
n2 = np.array([[1,2], [3,4], [5,6]])
print(n2)

[[1 2]
 [3 4]
 [5 6]]


In [18]:
print(n2.ndim) # 2

2


In [19]:
my_li1 = [-1,4]

my_li2 = [3,2]

my_li3 = [2,5]

my_li4 = [0,1]

my_lists = [my_li1,my_li2,my_li3,my_li4]

my_array3 = np.array(my_lists)

my_array3

array([[-1,  4],
       [ 3,  2],
       [ 2,  5],
       [ 0,  1]])